In [2]:
from pathlib import Path
import pandas as pd

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
#Inspecting the files position 
from pathlib import Path
import pandas as pd

# Locate the raw dataset folder
data_folder = Path("../data/raw")

# Find all CSV files
csv_files = sorted(data_folder.glob("*.csv"))

# Display the filenames
print("Number of CSV files found:", len(csv_files))

for file in csv_files:
    print(file.name)

Number of CSV files found: 2
ted_main.csv
transcripts.csv

In [4]:

# Load each CSV file into a separate DataFrame
datasets = {}

for file in csv_files:
    df = pd.read_csv(file, low_memory=False)
    datasets[file.stem] = df

    print("\n" + "=" * 60)
    print("Dataset:", file.name)
    print("Number of rows:", df.shape[0])
    print("Number of columns:", df.shape[1])
    print("Column names:")
    print(df.columns.tolist())

============================================================
Dataset: ted_main.csv
Number of rows: 2550
Number of columns: 17
Column names:
['comments', 'description', 'duration', 'event', 'film_date', 'languages', 'main_speaker', 'name', 'num_speaker', 'published_date', 'ratings', 'related_talks', 'speaker_occupation', 'tags', 'title', 'url', 'views']

============================================================
Dataset: transcripts.csv
Number of rows: 2467
Number of columns: 2
Column names:
['transcript', 'url']

In [5]:
#finding null values, duplicates  and first 5 rows for each dataset
for name, df in datasets.items():
    print("\n" + "=" * 60)
    print("Dataset:", name)

    print("\nData types and non-null counts:")
    df.info()

    print("\nMissing values per column:")
    print(df.isnull().sum().sort_values(ascending=False))

    print("\nDuplicate rows:", df.duplicated().sum())

    print("\nFirst 5 records:")
    display(df.head())

============================================================
Dataset: ted_main

Data types and non-null counts:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2550 entries, 0 to 2549
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   comments            2550 non-null   int64
 1   description         2550 non-null   object
 2   duration            2550 non-null   int64
 3   event               2550 non-null   object
 4   film_date           2550 non-null   int64
 5   languages           2550 non-null   int64
 6   main_speaker        2550 non-null   object
 7   name                2550 non-null   object
 8   num_speaker         2550 non-null   int64
 9   published_date      2550 non-null   int64
 10  ratings             2550 non-null   object
 11  related_talks       2550 non-null   object
 12  speaker_occupation  2544 non-null   object
 13  tags                2550 non-null   object
 14  title               2550 non-null   object
 15  url                 2550 non-null   object
 16  views               2550 non-null   int64
dtypes: int64(7), object(10)
memory usage: 338.8+ KB

Missing values per column:
speaker_occupation    6
comments              0
description           0
event                 0
duration              0
languages             0
main_speaker          0
name                  0
film_date             0
num_speaker           0
published_date        0
ratings               0
related_talks         0
tags                  0
title                 0
url                   0
views                 0
dtype: int64

Duplicate rows: 0

First 5 records:

,comments,description,duration,event,film_date,languages,main_speaker,name,num_speaker,published_date,ratings,related_talks,speaker_occupation,tags,title,url,views
0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,1140825600,60,Ken Robinson,Ken Robinson: Do schools kill creativity?,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110
1,265,With the same humor and humanity he exuded in ...,977,TED2006,1140825600,43,Al Gore,Al Gore: Averting the climate crisis,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","[{'id': 243, 'hero': 'https://pe.tedcdn.com/im...",Climate advocate,"['alternative energy', 'cars', 'climate change...",Averting the climate crisis,https://www.ted.com/talks/al_gore_on_averting_...,3200520
2,124,New York Times columnist David Pogue takes aim...,1286,TED2006,1140739200,26,David Pogue,David Pogue: Simplicity sells,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","[{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...",Technology columnist,"['computers', 'entertainment', 'interface desi...",Simplicity sells,https://www.ted.com/talks/david_pogue_says_sim...,1636292
3,200,"In an emotionally charged talk, MacArthur-winn...",1116,TED2006,1140912000,35,Majora Carter,Majora Carter: Greening the ghetto,1,1151367060,"[{'id': 3, 'name': 'Courageous', 'count': 760}...","[{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...",Activist for environmental justice,"['MacArthur grant', 'activism', 'business', 'c...",Greening the ghetto,https://www.ted.com/talks/majora_carter_s_tale...,1697550
4,593,You've never seen data presented like this. Wi...,1190,TED2006,1140566400,48,Hans Rosling,Hans Rosling: The best stats you've ever seen,1,1151440680,"[{'id': 9, 'name': 'Ingenious', 'count': 3202}...","[{'id': 2056, 'hero': 'https://pe.tedcdn.com/i...",Global health expert; data visionary,"['Africa', 'Asia', 'Google', 'demo', 'economic...",The best stats you've ever seen,https://www.ted.com/talks/hans_rosling_shows_t...,12005869

============================================================
Dataset: transcripts

Data types and non-null counts:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2467 entries, 0 to 2466
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   transcript  2467 non-null   object
 1   url         2467 non-null   object
dtypes: object(2)
memory usage: 38.7+ KB

Missing values per column:
transcript    0
url           0
dtype: int64

Duplicate rows: 3

First 5 records:

,transcript,url
0,Good morning. How are you?(Laughter)It's been ...,https://www.ted.com/talks/ken_robinson_says_sc...
1,"Thank you so much, Chris. And it's truly a gre...",https://www.ted.com/talks/al_gore_on_averting_...
2,"(Music: ""The Sound of Silence,"" Simon & Garfun...",https://www.ted.com/talks/david_pogue_says_sim...
3,If you're here today — and I'm very happy that...,https://www.ted.com/talks/majora_carter_s_tale...
4,"About 10 years ago, I took on the task to teac...",https://www.ted.com/talks/hans_rosling_shows_t...

In [6]:
# Standardize URL formatting for comparison
main = datasets["ted_main"].copy()
transcripts = datasets["transcripts"].copy()


main["url_key"] = main["url"].astype(str).str.strip().str.rstrip("/")
transcripts["url_key"] = (
    transcripts["url"].astype(str).str.strip().str.rstrip("/")
)


print("Duplicate metadata URLs:", main["url_key"].duplicated().sum())
print("Duplicate transcript URLs:", transcripts["url_key"].duplicated().sum())

main_urls = set(main["url_key"])
transcript_urls = set(transcripts["url_key"])

matching_urls = main_urls.intersection(transcript_urls)

print("\nUnique metadata URLs:", len(main_urls))
print("Unique transcript URLs:", len(transcript_urls))
print("URLs found in both datasets:", len(matching_urls))
print("Metadata URLs without transcripts:", len(main_urls - transcript_urls))

Duplicate metadata URLs: 0
Duplicate transcript URLs: 3

Unique metadata URLs: 2550
Unique transcript URLs: 2464
URLs found in both datasets: 2464
Metadata URLs without transcripts: 86

In [7]:
# Check duplicate URLs in transcripts
duplicate_transcripts = transcripts[
    transcripts["url_key"].duplicated(keep=False)
].sort_values("url_key")

print("Rows belonging to repeated URLs:", len(duplicate_transcripts))


duplicate_summary = (
    duplicate_transcripts.groupby("url_key")
    .agg(
        row_count=("transcript", "size"),
        unique_transcripts=("transcript", "nunique")
    )
    .reset_index()
)

display(duplicate_summary)

Rows belonging to repeated URLs: 6

,url_key,row_count,unique_transcripts
0,https://www.ted.com/talks/brene_brown_listenin...,2,1
1,https://www.ted.com/talks/jonathan_haidt_human...,2,1
2,https://www.ted.com/talks/rob_reid_the_8_billi...,2,1

In [8]:

quality_issues = pd.DataFrame([
    {
        "dataset": "ted_main",
        "issue": "Missing speaker_occupation",
        "count": 6,
        "planned_action": "Preserve the talks; fill missing occupations only if needed"
    },
    {
        "dataset": "transcripts",
        "issue": "Duplicate transcript URLs with identical text",
        "count": 3,
        "planned_action": "Keep one row per URL after confirming identical transcripts"
    },
    {
        "dataset": "combined data",
        "issue": "Metadata URLs without matching transcripts",
        "count": 86,
        "planned_action": "Keep metadata records; allow missing transcripts"
    }
])

display(quality_issues)

,dataset,issue,count,planned_action
0,ted_main,Missing speaker_occupation,6,Preserve the talks; fill missing occupations o...
1,transcripts,Duplicate transcript URLs with identical text,3,Keep one row per URL after confirming identica...
2,combined data,Metadata URLs without matching transcripts,86,Keep metadata records; allow missing transcripts

In [9]:
#romoving the duplicate urls .
transcripts_clean = transcripts.copy()

transcripts_clean = transcripts_clean.drop_duplicates(
    subset="url_key",
    keep="first"
)


print("Original transcript rows:", len(transcripts))
print("Cleaned transcript rows:", len(transcripts_clean))

print(
    "Duplicate URLs remaining:",
    transcripts_clean["url_key"].duplicated().sum()
)

Original transcript rows: 2467
Cleaned transcript rows: 2464
Duplicate URLs remaining: 0

In [10]:
#merging the two datasets on url_key to create a combined dataset

ted_combined = main.merge(
    transcripts_clean[["url_key", "transcript"]],
    on="url_key",
    how="left",
    validate="one_to_one"
)

print("Original metadata rows:", len(main))
print("Combined dataset rows:", len(ted_combined))
print("Missing transcripts:", ted_combined["transcript"].isna().sum())

display(
    ted_combined[
        ["title", "main_speaker", "url", "transcript"]
    ].head()
)

Original metadata rows: 2550
Combined dataset rows: 2550
Missing transcripts: 86

,title,main_speaker,url,transcript
0,Do schools kill creativity?,Ken Robinson,https://www.ted.com/talks/ken_robinson_says_sc...,Good morning. How are you?(Laughter)It's been ...
1,Averting the climate crisis,Al Gore,https://www.ted.com/talks/al_gore_on_averting_...,"Thank you so much, Chris. And it's truly a gre..."
2,Simplicity sells,David Pogue,https://www.ted.com/talks/david_pogue_says_sim...,"(Music: ""The Sound of Silence,"" Simon & Garfun..."
3,Greening the ghetto,Majora Carter,https://www.ted.com/talks/majora_carter_s_tale...,If you're here today — and I'm very happy that...
4,The best stats you've ever seen,Hans Rosling,https://www.ted.com/talks/hans_rosling_shows_t...,"About 10 years ago, I took on the task to teac..."

In [11]:

# Summary statistics for numerical columns
display(ted_combined.describe())

# Convert duration from seconds to minutes for easier interpretation
duration_minutes = ted_combined["duration"] / 60

print("Average talk duration (minutes):", round(duration_minutes.mean(), 2))
print("Shortest talk (minutes):", round(duration_minutes.min(), 2))
print("Longest talk (minutes):", round(duration_minutes.max(), 2))

print("\nTalks with zero or negative duration:",
      (ted_combined["duration"] <= 0).sum())

print("Talks with zero or negative views:",
      (ted_combined["views"] <= 0).sum())

,comments,duration,film_date,languages,num_speaker,published_date,views
count,2550.000000,2550.000000,2.550000e+03,2550.000000,2550.000000,2.550000e+03,2.550000e+03
mean,191.562353,826.510196,1.321928e+09,27.326275,1.028235,1.343525e+09,1.698297e+06
std,282.315223,374.009138,1.197391e+08,9.563452,0.207705,9.464009e+07,2.498479e+06
min,2.000000,135.000000,7.464960e+07,0.000000,1.000000,1.151367e+09,5.044300e+04
25%,63.000000,577.000000,1.257466e+09,23.000000,1.000000,1.268463e+09,7.557928e+05
50%,118.000000,848.000000,1.333238e+09,28.000000,1.000000,1.340935e+09,1.124524e+06
75%,221.750000,1046.750000,1.412964e+09,33.000000,1.000000,1.423432e+09,1.700760e+06
max,6404.000000,5256.000000,1.503792e+09,72.000000,5.000000,1.506092e+09,4.722711e+07

Average talk duration (minutes): 13.78
Shortest talk (minutes): 2.25
Longest talk (minutes): 87.6

Talks with zero or negative duration: 0
Talks with zero or negative views: 0

In [12]:

# Count available transcripts
available = ted_combined["transcript"].notna().sum()
missing = ted_combined["transcript"].isna().sum()

print("Transcripts available:", available)
print("Transcripts missing:", missing)
print("Transcript coverage (%):",
      round(available / len(ted_combined) * 100, 2))

# Calculate word counts for available transcripts
word_counts = ted_combined["transcript"].dropna().str.split().str.len()

print("\nAverage transcript word count:", round(word_counts.mean(), 2))
print("Shortest transcript (words):", word_counts.min())
print("Longest transcript (words):", word_counts.max())

Transcripts available: 2464
Transcripts missing: 86
Transcript coverage (%): 96.63

Average transcript word count: 2040.23
Shortest transcript (words): 1
Longest transcript (words): 9044

In [13]:
# Calculate the number of words in each available transcript and display talks with fewer than 20 transcript words
ted_combined["transcript_word_count"] = (
    ted_combined["transcript"]
    .fillna("")
    .str.split()
    .str.len()
)

short_transcripts = ted_combined[
    ted_combined["transcript_word_count"].between(1, 19)
]

print("Talks with 1–19 transcript words:", len(short_transcripts))

display(
    short_transcripts[
        ["title", "main_speaker", "transcript_word_count", "transcript"]
    ].head(10)
)

Talks with 1–19 transcript words: 10

,title,main_speaker,transcript_word_count,transcript
149,My magic moves,Kenichi Ebina,1,(Applause)(Music)(Applause)
310,Playing invisible turntables,James Burchfield,14,"Let's just get started here.Okay, just a momen..."
587,An all-star set,Herbie Hancock,19,(Music)(Applause)(Music)(Music) (Applause)(Mus...
946,"On violin and cello, ""Passacaglia""",Robert Gupta + Joshua Roman,1,(Music)(Applause)(Music)(Applause)
1248,Dancing with light,Quixotic Fusion,1,(Music)(Applause)(Music)(Applause)(Music)(Appl...
1444,"Dance, tiny robots!",Bruno Maisonnier,3,(Mechanical noises)(Music) (Applause)
1877,"A dance in a hurricane of paper, wind and light",Aakash Odedra,1,(Music)(Applause)
2000,An 11-year-old prodigy performs old-school jazz,Joey Alexander,2,(Music)(Music) (Applause)(Applause)
2081,A musical escape into a world of light and color,Kaki King,11,(Guitar music starts)(Music ends)(Applause)(Di...
2382,An electrifying acoustic guitar performance,Rodrigo y Gabriela,4,(Guitar music starts)(Cheers)(Cheers)(Music ends)

In [ ]:

# Summary statistics for important numeric columns
display(
    ted_combined[["duration", "views", "comments", "languages"]]
    .describe()
)

# Check for potentially invalid values
print("Duration <= 0:", (ted_combined["duration"] <= 0).sum())
print("Views <= 0:", (ted_combined["views"] <= 0).sum())
print("Comments < 0:", (ted_combined["comments"] < 0).sum())
print("Languages < 0:", (ted_combined["languages"] < 0).sum())

 Exploratory Data Analysis — Findings

1. Dataset overview

- The metadata dataset contains 2,550 TED talks.
- The transcript dataset originally contains 2,467 rows.
- After removing duplicate transcript URLs, 2,464 unique transcript records remain.
- The datasets were merged using normalized URLs, preserving all 2,550 metadata records.

2. Transcript coverage

- Talks with transcripts: 2,464.
- Talks without transcripts: 86.
- Transcript coverage: 96.63%.
- Missing transcripts will be preserved as empty text during preprocessing so that these talks can still be recommended using their available metadata.

3. Data quality issues and decisions

- Missing speaker occupations: 6 records in the metadata dataset.
- Duplicate transcript URLs: 3 duplicate records identified and removed after confirming identical transcript text.
- Missing transcript matches: 86 metadata records have no matching transcript.
- Very short transcripts: 10 talks have between 1 and 19 transcript words. These records will be retained because some are performances and can still be represented using titles, descriptions, and tags.

4. Numerical analysis

- Numerical summary statistics were inspected using `describe()`.
- Talk duration was converted from seconds to minutes for easier interpretation.
- Zero or negative durations and views were checked. The observed counts are recorded in the notebook output.

5. Preprocessing decision

The original metadata will be preserved. Duplicate transcript records will be removed, metadata and transcripts will be combined using normalized URLs, and missing text fields will be handled during feature preparation. The cleaned dataset will retain talks even when transcripts are unavailable.

In [16]:
# Create a separate copy for recommendation model preparation and fill missing text values with empty strings
ted_model_data = ted_combined.copy()

text_columns = ["title", "description", "tags", "transcript"]

for column in text_columns:
    ted_model_data[column] = ted_model_data[column].fillna("")

# Combine the available text fields into one column
ted_model_data["combined_text"] = (
    ted_model_data["title"] + " " +
    ted_model_data["description"] + " " +
    ted_model_data["tags"] + " " +
    ted_model_data["transcript"]
).str.strip()

# Check the prepared dataset
print("Dataset shape:", ted_model_data.shape)
print("Missing values in text columns:")
print(ted_model_data[text_columns].isna().sum())

display(
    ted_model_data[
        ["title", "description", "tags", "transcript", "combined_text"]
    ].head(3)
)

Dataset shape: (2550, 21)
Missing values in text columns:
title          0
description    0
tags           0
transcript     0
dtype: int64

,title,description,tags,transcript,combined_text
0,Do schools kill creativity?,Sir Ken Robinson makes an entertaining and pro...,"['children', 'creativity', 'culture', 'dance',...",Good morning. How are you?(Laughter)It's been ...,Do schools kill creativity? Sir Ken Robinson m...
1,Averting the climate crisis,With the same humor and humanity he exuded in ...,"['alternative energy', 'cars', 'climate change...","Thank you so much, Chris. And it's truly a gre...",Averting the climate crisis With the same humo...
2,Simplicity sells,New York Times columnist David Pogue takes aim...,"['computers', 'entertainment', 'interface desi...","(Music: ""The Sound of Silence,"" Simon & Garfun...",Simplicity sells New York Times columnist Davi...

In [17]:
# Check whether combined text was created correctly
print("Missing combined text values:",
      ted_model_data["combined_text"].isna().sum())

print("Empty combined text records:",
      (ted_model_data["combined_text"].str.len() == 0).sum())

print("\nSample combined text:")
print(ted_model_data["combined_text"].iloc[0][:500])

Missing combined text values: 0
Empty combined text records: 0

Sample combined text:
Do schools kill creativity? Sir Ken Robinson makes an entertaining and profoundly moving case for creating an education system that nurtures (rather than undermines) creativity. ['children', 'creativity', 'culture', 'dance', 'education', 'parenting', 'teaching'] Good morning. How are you?(Laughter)It's been great, hasn't it? I've been blown away by the whole thing. In fact, I'm leaving.(Laughter)There have been three themes running through the conference which are relevant to what I want to talk

In [18]:
# Save the prepared dataset to a CSV file in the dta/processed folder
from pathlib import Path


output_path = Path("../data/processed/ted_processed.csv")
ted_model_data.to_csv(output_path, index=False)

# Confirm the file was created
print("Dataset saved to:", output_path)
print("File exists:", output_path.exists())

Dataset saved to: ..\data\processed\ted_processed.csv
File exists: True